# 出库管理服务配置（出库单 + Feign 调用库存服务）
server:
  port: 8022
spring:
  application:
    name: outbound-service
  # 激活 profile:打包时用 -Dp.env=dev(本地)或 -Dp.env=k8s(集群)切换
  profiles:
    active: ${p.env}
eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
