# 库存预警服务配置（检查库存低于安全库存，生成预警记录）
server:
  port: 8023
spring:
  application:
    name: alert-service
  # 激活 profile:打包时用 -Dp.env=dev(本地)或 -Dp.env=k8s(集群)切换
  profiles:
    active: ${p.env}
eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
