FROM docker.m.daocloud.io/library/eclipse-temurin:8-jre-alpine
LABEL maintainer=me
ENV JAVA_ARGS="-Dfile.encoding=UTF8 -Duser.timezone=GMT+08"
ENV JAR_FILE="inbound-service.jar"
COPY ./${JAR_FILE} ./
EXPOSE 8021
CMD java -jar ${JAVA_ARGS} ${JAVA_OPTS} /${JAR_FILE}
