# 库存统计服务配置（聚合入库/出库/库存生成日报表）
server:
  port: 8024
spring:
  application:
    name: statistics-service
  # 激活 profile:打包时用 -Dp.env=dev(本地)或 -Dp.env=k8s(集群)切换
  profiles:
    active: ${p.env}
eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
